baseURL: "https://blog.kyledev.co"
title: blog.kyledev.co
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-EPT6LGCQ2D

minify:
  disableXML: true
  minifyOutput: false

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Posts
          url: posts/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "a blog about the random tech things I do at home"
  author: Kyle Wilson

  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images: []

  profileMode:
    enabled: false

  homeInfoParams:
    Title: "Kyle Wilson"
    Content: >
      Welcome to my blog. I do a lot of homelab things with raspberry pis.

  socialIcons:
    - name: github
      url: "https://github.com/kdwils"
    - name: Rss
      url: "index.xml"
    - name: linkedin
      url: "https://www.linkedin.com/in/kyle-wilson-/"

  editPost:
    URL: "https://github.com/kdwils/blog/tree/main/content/"
    Text: "Suggest Changes"
    appendFilePath: true

  assets:
    disableHLJS: false

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    # lineNos: true
    style: monokai-sublime

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: true
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
