apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: blog=ghcr.io/kdwils/blog:live
    argocd-image-updater.argoproj.io/blog.platforms: linux/arm64,linux/amd64
    argocd-image-updater.argoproj.io/blog.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: blog
    server: "https://kubernetes.default.svc"
  source:
    path: deploy/prod
    repoURL: "https://github.com/kdwils/blog"
    targetRevision: prod
  sources: []
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
