apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      annotations:
        backstage.io/kubernetes-id: blog
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          imagePullPolicy: Always
          image: ghcr.io/kdwils/blog:main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
