kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - service.yaml
  - namespace.yaml
  - rollout.yaml
  - ingress.yaml
  - gateway.yaml
  - virtualservice.yaml
  - destinationrule.yaml
