apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
  namespace: blog
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blog
  strategy:
    blueGreen:
      activeService: blog
      autoPromotionEnabled: false
      previewReplicaCount: 1
      previewService: blog-preview
  template:
    metadata:
      labels:
        app: blog
        backstage.io/kubernetes-id: blog
    spec:
      containers:
        - image: ghcr.io/kdwils/blog:main
          imagePullPolicy: Always
          name: blog-rollouts-demo
          ports:
            - containerPort: 8080
              name: http
