apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
        backstage.io/kubernetes-id: blog
    spec:
      containers:
        - name: blog-rollouts-demo
          image: ghcr.io/kdwils/blog:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
  strategy:
    blueGreen:
      activeService: blog
      previewService: blog-preview
      autoPromotionEnabled: false
      previewReplicaCount: 1
