apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "blog"
    backstage.io/kubernetes-id: blog
spec:
  selector:
    app: blog
  ports:
    - port: 80
      name: http
      targetPort: 8080
  type: LoadBalancer
  loadBalancerClass: tailscale
