kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - httproute.yaml
  - blog.yaml
  - vpa.yaml

images:
  - name: blog
    newName: ghcr.io/kdwils/blog
    newTag: sha-4386052465ccceaf0205190f4cf9472bf964714a
