kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - httproute.yaml
  - blog.yaml
  - vpa.yaml

images:
  - name: blog
    newName: ghcr.io/kdwils/blog
    newTag: sha256:d11cd40516d59c6534974b40521f5ca18c963cf21409207a3621c4af1a46bcfe
