apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: blog
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: blog
      sources:
        direct: true
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: blog-dev
        sourceUpdates:
          - repoURL: https://github.com/kdwils/blog.git
            git:
              branch: dev
