kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - vpa.yaml
images:
  - name: blog
    newName: ghcr.io/kdwils/blog
    newTag: prod
