kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - blog.yaml
  - httproute.yaml
  - namespace.yaml
  # - vpa.yaml

images:
  - name: blog
    newName: ghcr.io/kdwils/blog
    newTag: live
