kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - blog.yaml

images:
  - name: blog
    newName: ghcr.io/kdwils/blog
    newTag: dev
  - name: blog-prod
    newName: ghcr.io/kdwils/blog
    newTag: prod
