---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: blog
  namespace: blog
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: blog
  namespace: blog
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/kdwils/blog.git
        branch: main
---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
