name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  release_please:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: kdwils/homelab-workflow/.github/workflows/release-please.yml@main

  build_push_sign:
    needs: release_please
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: kdwils/homelab-workflow/.github/workflows/build-push-sign.yml@main
        with:
          image: kdwils/blog
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64
          dockerfile: Dockerfile
