name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  release_please:
    if: github.event_name == 'push'
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    uses: kdwils/homelab-workflow/.github/workflows/release-please.yml@main

  build_push_docker_image:
    needs: release_please
    if: github.ref_type == 'tag'
    uses: kdwils/homelab-workflow/.github/workflows/build-push-sign.yml@main
    secrets: inherit
    with:
      image: kdwils/blog
      registry: ghcr.io
      platforms: linux/amd64,linux/arm64
