name: pr

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: kdwils/homelab-workflow/.github/workflows/build-image.yml@main
        with:
          platforms: linux/amd64,linux/arm64
          dockerfile: Dockerfile
